<?php
ini_set("display_errors", true);
date_default_timezone_set("Europe/London");

// Retrieve entries for each server, these logs are generated by ping.sh
$array101all = file('tmp/ping.log.192.168.99.101');
$array102all = file('tmp/ping.log.192.168.99.102');
$array103all = file('tmp/ping.log.192.168.99.103');
$array104all = file('tmp/ping.log.192.168.99.104');
$array105all = file('tmp/ping.log.192.168.99.105');
$array106all = file('tmp/ping.log.192.168.99.106');
$array107all = file('tmp/ping.log.192.168.99.107');
$array108all = file('tmp/ping.log.192.168.99.108');

$timearray = array();
$auto_refresh=1;


// pull out the time of each of the ping request and assign to an array
foreach($array101all as $time) {
	$timearray[] = substr($time, 0, 5);
}

// remove the time and bring back only the ping result
foreach($array101all as $status) {
	$array101[] = substr($status, 5);
}
foreach($array102all as $status) {
	$array102[] = substr($status, 5);
}
foreach($array103all as $status) {
	$array103[] = substr($status, 5);
}
foreach($array104all as $status) {
	$array104[] = substr($status, 5);
}
foreach($array105all as $status) {
	$array105[] = substr($status, 5);
}
foreach($array106all as $status) {
	$array106[] = substr($status, 5);
}
foreach($array107all as $status) {
	$array107[] = substr($status, 5);
}
foreach($array108all as $status) {
	$array108[] = substr($status, 5);
}

// create arrays to be used in table

$config_net_data[]=array("name"=>"amativ01-mail",	  "IP"=>"192.168.99.101",$timearray[0]=>$array101[0],$timearray[1]=>$array101[1],$timearray[2]=>$array101[2],$timearray[3]=>$array101[3],$timearray[4]=>$array101[4],$timearray[5]=>$array101[5],$timearray[6]=>$array101[6],$timearray[7]=>$array101[7],$timearray[8]=>$array101[8],$timearray[9]=>$array101[9],$timearray[10]=>$array101[10],$timearray[11]=>$array101[11],$timearray[12]=>$array101[12],$timearray[13]=>$array101[13],$timearray[14]=>$array101[14],$timearray[15]=>$array101[15],$timearray[16]=>$array101[16],$timearray[17]=>$array101[17],$timearray[18]=>$array101[18],$timearray[19]=>$array101[19],$timearray[20]=>$array101[20],$timearray[21]=>$array101[21],$timearray[22]=>$array101[22],$timearray[23]=>$array101[23],$timearray[24]=>$array101[24],$timearray[25]=>$array101[25],$timearray[26]=>$array101[26],$timearray[27]=>$array101[27],$timearray[28]=>$array101[28],$timearray[29]=>$array101[29]);
$config_net_data[]=array("name"=>"amativ02-mailpiler",	  "IP"=>"192.168.99.102",$timearray[0]=>$array102[0],$timearray[1]=>$array102[1],$timearray[2]=>$array102[2],$timearray[3]=>$array102[3],$timearray[4]=>$array102[4],$timearray[5]=>$array102[5],$timearray[6]=>$array102[6],$timearray[7]=>$array102[7],$timearray[8]=>$array102[8],$timearray[9]=>$array102[9],$timearray[10]=>$array102[10],$timearray[11]=>$array102[11],$timearray[12]=>$array102[12],$timearray[13]=>$array102[13],$timearray[14]=>$array102[14],$timearray[15]=>$array102[15],$timearray[16]=>$array102[16],$timearray[17]=>$array102[17],$timearray[18]=>$array102[18],$timearray[19]=>$array102[19],$timearray[20]=>$array102[20],$timearray[21]=>$array102[21],$timearray[22]=>$array102[22],$timearray[23]=>$array102[23],$timearray[24]=>$array102[24],$timearray[25]=>$array102[25],$timearray[26]=>$array102[26],$timearray[27]=>$array102[27],$timearray[28]=>$array102[28],$timearray[29]=>$array102[29]);
$config_net_data[]=array("name"=>"amativ03-vpn",	  "IP"=>"192.168.99.103",$timearray[0]=>$array103[0],$timearray[1]=>$array103[1],$timearray[2]=>$array103[2],$timearray[3]=>$array103[3],$timearray[4]=>$array103[4],$timearray[5]=>$array103[5],$timearray[6]=>$array103[6],$timearray[7]=>$array103[7],$timearray[8]=>$array103[8],$timearray[9]=>$array103[9],$timearray[10]=>$array103[10],$timearray[11]=>$array103[11],$timearray[12]=>$array103[12],$timearray[13]=>$array103[13],$timearray[14]=>$array103[14],$timearray[15]=>$array103[15],$timearray[16]=>$array103[16],$timearray[17]=>$array103[17],$timearray[18]=>$array103[18],$timearray[19]=>$array103[19],$timearray[20]=>$array103[20],$timearray[21]=>$array103[21],$timearray[22]=>$array103[22],$timearray[23]=>$array103[23],$timearray[24]=>$array103[24],$timearray[25]=>$array103[25],$timearray[26]=>$array103[26],$timearray[27]=>$array103[27],$timearray[28]=>$array103[28],$timearray[29]=>$array103[29]);
$config_net_data[]=array("name"=>"amativ04-otherservices","IP"=>"192.168.99.104",$timearray[0]=>$array104[0],$timearray[1]=>$array104[1],$timearray[2]=>$array104[2],$timearray[3]=>$array104[3],$timearray[4]=>$array104[4],$timearray[5]=>$array104[5],$timearray[6]=>$array104[6],$timearray[7]=>$array104[7],$timearray[8]=>$array104[8],$timearray[9]=>$array104[9],$timearray[10]=>$array104[10],$timearray[11]=>$array104[11],$timearray[12]=>$array104[12],$timearray[13]=>$array104[13],$timearray[14]=>$array104[14],$timearray[15]=>$array104[15],$timearray[16]=>$array104[16],$timearray[17]=>$array104[17],$timearray[18]=>$array104[18],$timearray[19]=>$array104[19],$timearray[20]=>$array104[20],$timearray[21]=>$array104[21],$timearray[22]=>$array104[22],$timearray[23]=>$array104[23],$timearray[24]=>$array104[24],$timearray[25]=>$array104[25],$timearray[26]=>$array104[26],$timearray[27]=>$array104[27],$timearray[28]=>$array104[28],$timearray[29]=>$array104[29]);
$config_net_data[]=array("name"=>"amativ05-apps2", 	  "IP"=>"192.168.99.105",$timearray[0]=>$array105[0],$timearray[1]=>$array105[1],$timearray[2]=>$array105[2],$timearray[3]=>$array105[3],$timearray[4]=>$array105[4],$timearray[5]=>$array105[5],$timearray[6]=>$array105[6],$timearray[7]=>$array105[7],$timearray[8]=>$array105[8],$timearray[9]=>$array105[9],$timearray[10]=>$array105[10],$timearray[11]=>$array105[11],$timearray[12]=>$array105[12],$timearray[13]=>$array105[13],$timearray[14]=>$array105[14],$timearray[15]=>$array105[15],$timearray[16]=>$array105[16],$timearray[17]=>$array105[17],$timearray[18]=>$array105[18],$timearray[19]=>$array105[19],$timearray[20]=>$array105[20],$timearray[21]=>$array105[21],$timearray[22]=>$array105[22],$timearray[23]=>$array105[23],$timearray[24]=>$array105[24],$timearray[25]=>$array105[25],$timearray[26]=>$array105[26],$timearray[27]=>$array105[27],$timearray[28]=>$array105[28],$timearray[29]=>$array105[29]);
$config_net_data[]=array("name"=>"amativ06-www2",	  "IP"=>"192.168.99.106",$timearray[0]=>$array106[0],$timearray[1]=>$array106[1],$timearray[2]=>$array106[2],$timearray[3]=>$array106[3],$timearray[4]=>$array106[4],$timearray[5]=>$array106[5],$timearray[6]=>$array106[6],$timearray[7]=>$array106[7],$timearray[8]=>$array106[8],$timearray[9]=>$array106[9],$timearray[10]=>$array106[10],$timearray[11]=>$array106[11],$timearray[12]=>$array106[12],$timearray[13]=>$array106[13],$timearray[14]=>$array106[14],$timearray[15]=>$array106[15],$timearray[16]=>$array106[16],$timearray[17]=>$array106[17],$timearray[18]=>$array106[18],$timearray[19]=>$array106[19],$timearray[20]=>$array106[20],$timearray[21]=>$array106[21],$timearray[22]=>$array106[22],$timearray[23]=>$array106[23],$timearray[24]=>$array106[24],$timearray[25]=>$array106[25],$timearray[26]=>$array106[26],$timearray[27]=>$array106[27],$timearray[28]=>$array106[28],$timearray[29]=>$array106[29]);
$config_net_data[]=array("name"=>"amativ07-HPConnect",	  "IP"=>"192.168.99.107",$timearray[0]=>$array107[0],$timearray[1]=>$array107[1],$timearray[2]=>$array107[2],$timearray[3]=>$array107[3],$timearray[4]=>$array107[4],$timearray[5]=>$array107[5],$timearray[6]=>$array107[6],$timearray[7]=>$array107[7],$timearray[8]=>$array107[8],$timearray[9]=>$array107[9],$timearray[10]=>$array107[10],$timearray[11]=>$array107[11],$timearray[12]=>$array107[12],$timearray[13]=>$array107[13],$timearray[14]=>$array107[14],$timearray[15]=>$array107[15],$timearray[16]=>$array107[16],$timearray[17]=>$array107[17],$timearray[18]=>$array107[18],$timearray[19]=>$array107[19],$timearray[20]=>$array107[20],$timearray[21]=>$array107[21],$timearray[22]=>$array107[22],$timearray[23]=>$array107[23],$timearray[24]=>$array107[24],$timearray[25]=>$array107[25],$timearray[26]=>$array107[26],$timearray[27]=>$array107[27],$timearray[28]=>$array107[28],$timearray[29]=>$array107[29]);
$config_net_data[]=array("name"=>"amativ08-Mattermost",   "IP"=>"192.168.99.108",$timearray[0]=>$array108[0],$timearray[1]=>$array108[1],$timearray[2]=>$array108[2],$timearray[3]=>$array108[3],$timearray[4]=>$array108[4],$timearray[5]=>$array108[5],$timearray[6]=>$array108[6],$timearray[7]=>$array108[7],$timearray[8]=>$array108[8],$timearray[9]=>$array108[9],$timearray[10]=>$array108[10],$timearray[11]=>$array108[11],$timearray[12]=>$array108[12],$timearray[13]=>$array108[13],$timearray[14]=>$array108[14],$timearray[15]=>$array108[15],$timearray[16]=>$array108[16],$timearray[17]=>$array108[17],$timearray[18]=>$array108[18],$timearray[19]=>$array108[19],$timearray[20]=>$array108[20],$timearray[21]=>$array108[21],$timearray[22]=>$array108[22],$timearray[23]=>$array108[23],$timearray[24]=>$array108[24],$timearray[25]=>$array108[25],$timearray[26]=>$array108[26],$timearray[27]=>$array108[27],$timearray[28]=>$array108[28],$timearray[29]=>$array108[29]);

// html title for above table and also defining the table border
$html_title = '<H2>Server Monitor</H2>';
$table_html = "<TABLE border=\"2\">\n";

// create column headers
$config_table_columns = array('name', 'IP', $timearray[0], $timearray[1], $timearray[2],$timearray[3],$timearray[4],$timearray[5],$timearray[6],$timearray[7],$timearray[8],$timearray[9],$timearray[10],$timearray[11],$timearray[12],$timearray[13],$timearray[14],$timearray[15],$timearray[16],$timearray[17],$timearray[18],$timearray[19],$timearray[20],$timearray[21],$timearray[22],$timearray[23],$timearray[24],$timearray[25],$timearray[26],$timearray[27],$timearray[28],$timearray[29]);

flush();

// function for status column - pings all hosts

function ping($host) {
    if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
        //echo 'This is a server using Windows!';
        exec(sprintf('ping -n 1 -w 5 %s', escapeshellarg($host)), $res, $rval);
    } else {
        //echo 'This is a server not using Windows!';
        exec(sprintf('ping -c 1 -W 1 %s', escapeshellarg($host)), $res, $rval);
    }
    return $rval === 0;
}

// contruct the table

	$table_row = "\n<TR>";
	foreach ($config_table_columns as $key => $column_heading) {
		$table_row .= '<TD>' . $column_heading . '</TD>';
	}
	$table_row .= '<TD>status</TD>';
	$table_html .= $table_row . "</TR>\n";
	foreach ($config_net_data as $device_key => $device_values) {
		$table_row = "\n<TR>";
		$device_name = $device_values['name'];
		//$status_cell = '<TD>&nbsp;</TD>';
		if(ping($device_values['IP'])=='on') {
			$status_cell = "<TD style=\"background-color:green\">ON</TD>";
		} else { 
			$status_cell = "<TD style=\"background-color:red\">OFF</TD>";
		}
		
		foreach ($config_table_columns as $key => $column_heading) {
			if (isset ( $device_values[$column_heading])) {
				$value = $device_values[$column_heading];
			} else {
				$value = '';
			}
			if ($value === '') {
				$value = '&nbsp;';
			}
			$table_row .= '<TD>' . $value . '</TD>';
		}
		$table_row .= $status_cell;
		$table_html .= $table_row . "</TR>\n";
	}
	$table_html .= "</TABLE>\n";


// html
	
echo "<!DOCTYPE html>\n";
echo "<html>\n";
echo "<head>\n";
if(isset($auto_refresh) && $auto_refresh==1) {
    echo "<meta http-equiv=\"refresh\" content=\"60;url=".$_SERVER['PHP_SELF']."\" />\n";
}
echo "</head>\n";
echo "<body>\n";
echo $html_title;
echo $table_html;
echo "<p>The above shows the last 30 ping attempts to each of the servers - the ping attempts happen once per minute.</p>";
echo "<p>This page auto refreshes once per minute.</p>";
if (isset($_POST['button'])) { shell_exec("/mainMode.sh"); }
echo "<form action=\"\" method=\"post\">";
echo "<button type=\"submit\" name=\"button\"> Maintenance Mode</button>";
echo "</form>";

echo "</body>\n";
echo "</html>\n";
echo date("H:i:s");
?>

